-- ============================================================
-- NOTIFICACIONES PUSH — ejecutar DESPUES de "-- Tabla de Horarios.sql"
-- ============================================================
-- Que hace este archivo:
--   1) Tabla para guardar los dispositivos que activaron notificaciones.
--   2) Un lugar privado (no accesible desde el navegador) para guardar
--      la URL de la Edge Function y un secreto compartido con ella.
--   3) Una funcion que sabe "en que semana y que dia estamos" (igual
--      que el codigo del navegador) para usarla desde la base de datos.
--   4) Un trigger: cuando se guarda o cambia una tarea, se avisa.
--   5) pg_cron: a la hora exacta de cada clase, si hay tarea, se avisa.
--   6) pg_cron: todos los dias a las 5:30am (hora Bogota) se manda el
--      resumen de tareas del dia.
--
-- IMPORTANTE: antes de correr esto, despliega la Edge Function
-- "send-push" (ver README-notificaciones.md) y ten a la mano:
--   - La URL de tu Edge Function, algo como:
--     https://TU_PROYECTO.functions.supabase.co/send-push
--   - Un secreto (cualquier texto largo y aleatorio) que tambien
--     configures como variable de entorno CRON_SECRET en la funcion.
-- ============================================================

-- 1) Suscripciones push (una fila por dispositivo/navegador) ---------
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text unique not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "anon puede suscribirse" on public.push_subscriptions;
create policy "anon puede suscribirse"
  on public.push_subscriptions for insert
  to anon, authenticated
  with check (true);

drop policy if exists "anon puede actualizar su suscripcion" on public.push_subscriptions;
create policy "anon puede actualizar su suscripcion"
  on public.push_subscriptions for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "anon puede darse de baja" on public.push_subscriptions;
create policy "anon puede darse de baja"
  on public.push_subscriptions for delete
  to anon, authenticated
  using (true);
-- (Sin politica de SELECT para anon: nadie puede listar los suscritos
--  de otras personas desde el navegador; solo la Edge Function, que
--  usa la service_role key, puede leerlos.)

-- 2) Configuracion privada (URL de la funcion + secreto) --------------
create schema if not exists private;

create table if not exists private.app_secrets (
  key text primary key,
  value text not null
);
alter table private.app_secrets enable row level security;
-- Sin politicas = nadie via API puede leer esta tabla. Solo funciones
-- SECURITY DEFINER (dueñas: postgres) pueden acceder a ella.

-- Reemplaza estos dos valores por los tuyos antes de ejecutar:
insert into private.app_secrets (key, value) values
  ('edge_function_url', 'https://REEMPLAZA-TU-PROYECTO.functions.supabase.co/send-push'),
  ('cron_secret', 'REEMPLAZA-POR-UN-SECRETO-LARGO-Y-ALEATORIO')
on conflict (key) do update set value = excluded.value;

-- Extensiones necesarias para llamar HTTP desde Postgres y programar tareas
create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron with schema extensions;

-- Funcion que llama a la Edge Function (uso interno, no expuesta)
create or replace function private.notify_push(payload jsonb)
returns void
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_url text;
  v_secret text;
begin
  select value into v_url    from private.app_secrets where key = 'edge_function_url';
  select value into v_secret from private.app_secrets where key = 'cron_secret';

  if v_url is null or v_url like '%REEMPLAZA%' then
    raise notice 'notify_push: configura edge_function_url en private.app_secrets antes de usar notificaciones';
    return;
  end if;

  perform net.http_post(
    url := v_url,
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
    body := payload
  );
end;
$$;
revoke all on function private.notify_push(jsonb) from public;

-- 3) Nombre de materia a partir de la celda (igual que MATS en el JS) --
create or replace function public.subject_name(p_cell_key text)
returns text language sql immutable as $$
  select case p_cell_key
    when '0-0' then 'Informática' when '0-1' then 'Matemáticas' when '0-2' then 'Física'    when '0-3' then 'Filosofía'
    when '1-0' then 'Robótica'    when '1-1' then 'Español'     when '1-2' then 'Español'    when '1-3' then 'Español'
    when '2-0' then 'Inglés'      when '2-1' then 'Física'      when '2-2' then 'Geometría'  when '2-3' then 'Inglés'
    when '3-0' then 'Política'    when '3-1' then 'Ética'       when '3-2' then 'Inglés'     when '3-3' then 'Español'
    when '4-0' then 'Matemáticas' when '4-1' then 'Ciencias'    when '4-2' then 'Física'     when '4-3' then 'Artística'
    when '5-0' then 'Inglés'      when '5-1' then 'Inglés'      when '5-2' then 'Sociales'   when '5-3' then 'Matemáticas'
    when '6-0' then 'Química'     when '6-1' then 'Química'     when '6-2' then 'Filosofía'  when '6-3' then 'Estadística'
    when '7-0' then 'Edu. Física' when '7-1' then 'Economía'    when '7-2' then 'Química'    when '7-3' then 'Religión'
    else (case when p_cell_key like 'mil-%' then 'Fase Militar' else 'Materia' end)
  end;
$$;

-- Semana actual, calculada igual que ANCHOR_WEEK/ANCHOR_MON en index.html
-- (semana 21 = lunes 6 de julio de 2026). Si cambias el ancla en el JS,
-- cambia tambien aqui.
create or replace function public.current_week_number()
returns int language sql stable as $$
  select greatest(1, 21 + floor(
    ((now() at time zone 'America/Bogota')::date - date '2026-07-06') / 7.0
  )::int);
$$;

-- Columna del dia de hoy: 0=Lunes ... 4=Viernes (5/6 = fin de semana)
create or replace function public.today_day_col()
returns int language sql stable as $$
  select (extract(isodow from (now() at time zone 'America/Bogota'))::int - 1);
$$;

-- 4) Trigger: nueva tarea o cambio en una tarea existente --------------
create or replace function public.trg_schedule_change()
returns trigger
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_subject text;
  v_is_new boolean;
  v_is_postpone boolean;
  v_meaningful_change boolean;
  v_type text;
  v_noun text;
  v_gender text; -- 'f' = femenino (tarea), 'm' = masculino (examen/reclamo)
  v_icon text;
  v_title text;
begin
  if TG_OP = 'DELETE' then
    return old;
  end if;

  if NEW.task is null or btrim(NEW.task) = '' then
    return NEW; -- se vacio la celda, no notificar
  end if;

  v_is_new := (TG_OP = 'INSERT');
  -- El flujo de "Aplazar" en la app borra la fila vieja y crea una
  -- nueva, marcando las notas con este prefijo; asi lo distinguimos
  -- de una tarea realmente nueva.
  v_is_postpone := v_is_new and NEW.notes ilike 'Aplazada para las%';

  v_meaningful_change :=
    v_is_new
    or (OLD.task is distinct from NEW.task)
    or (OLD.due_date is distinct from NEW.due_date)
    or (OLD.instructor is distinct from NEW.instructor);

  if not v_meaningful_change then
    -- Solo cambio de estado (pendiente/entregada/etc): no generar push
    -- para evitar avisos por cada clic de estado.
    return NEW;
  end if;

  v_subject := coalesce(public.subject_name(NEW.cell_key), 'Materia');
  v_type := coalesce(NEW.type, 'tarea');

  case v_type
    when 'examen'  then v_noun := 'examen';  v_gender := 'm'; v_icon := '📝';
    when 'reclamo' then v_noun := 'reclamo'; v_gender := 'm'; v_icon := '🚩';
    else                v_noun := 'tarea';   v_gender := 'f'; v_icon := '📌';
  end case;

  if v_is_postpone then
    v_title := '📆 ' || initcap(v_noun) || (case when v_gender = 'f' then ' aplazada: ' else ' aplazado: ' end) || v_subject;
  elsif v_is_new then
    v_title := v_icon || ' ' || (case when v_gender = 'f' then 'Nueva ' else 'Nuevo ' end) || v_noun || ': ' || v_subject;
  else
    v_title := '✏️ ' || initcap(v_noun) || (case when v_gender = 'f' then ' modificada: ' else ' modificado: ' end) || v_subject;
  end if;

  perform private.notify_push(jsonb_build_object(
    'title', v_title,
    'body', NEW.task || case when NEW.due_date is not null then (E'\nPlazo: ' || to_char(NEW.due_date, 'DD/MM/YYYY')) else '' end,
    'tag', 'task-' || NEW.cell_key,
    'urgency', 'high',
    'url', './'
  ));

  return NEW;
end;
$$;

drop trigger if exists on_schedule_change on public.schedules;
create trigger on_schedule_change
after insert or update on public.schedules
for each row execute function public.trg_schedule_change();

-- 5) Aviso al empezar cada clase, si hay tarea pendiente para ella -----
create or replace function public.notify_class_start(p_block_idx text, p_is_militar boolean)
returns void
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_col int := public.today_day_col();
  v_week int := public.current_week_number();
  v_key text;
  v_row public.schedules%rowtype;
  v_subject text;
begin
  if v_col < 0 or v_col > 4 then
    return; -- fin de semana, no hay clases
  end if;

  if p_is_militar then
    v_key := 'mil-' || v_col;
  else
    if v_col > 3 then
      return; -- viernes solo tiene Fase Militar
    end if;
    v_key := p_block_idx || '-' || v_col;
  end if;

  select * into v_row from public.schedules where week_number = v_week and cell_key = v_key;
  if not found or v_row.task is null or btrim(v_row.task) = '' then
    return; -- no hay tarea pendiente para esta clase
  end if;

  v_subject := coalesce(public.subject_name(v_key), 'Materia');

  perform private.notify_push(jsonb_build_object(
    'title', '🔔 Empieza ' || v_subject,
    'body', 'Tienes ' || coalesce(v_row.type, 'tarea') || ' pendiente: ' || v_row.task,
    'tag', 'class-' || v_key,
    'urgency', 'high',
    'url', './'
  ));
end;
$$;

-- 6) Resumen diario a las 5:30am (hora Bogota) --------------------------
create or replace function public.notify_daily_summary()
returns void
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_week int := public.current_week_number();
  v_col int := public.today_day_col();
  v_lines text := '';
  v_count int := 0;
  v_subject text;
  r record;
begin
  if v_col < 0 or v_col > 4 then
    return; -- fin de semana
  end if;

  for r in
    select * from public.schedules
    where week_number = v_week
      and task is not null and btrim(task) <> ''
      and (
        cell_key = 'mil-' || v_col
        or (v_col <= 3 and cell_key like '%-' || v_col::text and cell_key not like 'mil-%')
      )
    order by cell_key
  loop
    v_subject := coalesce(public.subject_name(r.cell_key), 'Materia');
    v_lines := v_lines || '• [' || upper(coalesce(r.type, 'tarea')) || '] ' || v_subject || ': ' || r.task || E'\n';
    v_count := v_count + 1;
  end loop;

  if v_count = 0 then
    v_lines := 'No tienes tareas pendientes para hoy. ¡Buen día! 🎉';
  end if;

  perform private.notify_push(jsonb_build_object(
    'title', '☀️ Tareas de hoy (' || v_count || ')',
    'body', v_lines,
    'tag', 'daily-summary',
    'urgency', 'high',
    'url', './'
  ));
end;
$$;

-- 7) Programar los avisos con pg_cron -----------------------------------
-- Bogota es UTC-5 todo el año (sin horario de verano), por eso las horas
-- UTC de abajo son siempre "hora local + 5".
do $$
declare
  v_jobname text;
begin
  for v_jobname in
    select unnest(array[
      'daily-tasks-summary',
      'class-start-0','class-start-1','class-start-2','class-start-3',
      'class-start-4','class-start-5','class-start-6','class-start-7',
      'class-start-militar'
    ])
  loop
    perform cron.unschedule(jobid) from cron.job where jobname = v_jobname;
  end loop;
end $$;

-- Resumen diario: 5:30am Bogota = 10:30 UTC
select cron.schedule('daily-tasks-summary', '30 10 * * *',
  $$select public.notify_daily_summary();$$);

-- Inicio de cada bloque de clase, Lunes a Jueves (dow 1-4)
select cron.schedule('class-start-0', '0 12 * * 1-4',  $$select public.notify_class_start('0', false);$$); -- 7:00
select cron.schedule('class-start-1', '50 12 * * 1-4', $$select public.notify_class_start('1', false);$$); -- 7:50
select cron.schedule('class-start-2', '40 13 * * 1-4', $$select public.notify_class_start('2', false);$$); -- 8:40
select cron.schedule('class-start-3', '50 14 * * 1-4', $$select public.notify_class_start('3', false);$$); -- 9:50
select cron.schedule('class-start-4', '40 15 * * 1-4', $$select public.notify_class_start('4', false);$$); -- 10:40
select cron.schedule('class-start-5', '30 16 * * 1-4', $$select public.notify_class_start('5', false);$$); -- 11:30
select cron.schedule('class-start-6', '50 17 * * 1-4', $$select public.notify_class_start('6', false);$$); -- 12:50
select cron.schedule('class-start-7', '40 18 * * 1-4', $$select public.notify_class_start('7', false);$$); -- 13:40

-- Fase Militar: Lunes a Viernes (dow 1-5), empieza 2:30pm
select cron.schedule('class-start-militar', '30 19 * * 1-5', $$select public.notify_class_start(null, true);$$);
