-- ============================================================
-- Tabla principal para Horario y Tareas
-- ============================================================
CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_number INTEGER NOT NULL,
    cell_key TEXT NOT NULL, -- Ej: "0-0" para materia, "mil-1" para militar
    task TEXT,
    due_date DATE,
    instructor TEXT,
    type TEXT DEFAULT 'tarea',
    notes TEXT,
    status TEXT DEFAULT 'pendiente',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(week_number, cell_key)
);

-- Si la tabla ya existía sin estas columnas (la app las necesita
-- para guardar tipo, notas y estado de cada tarea), agrégalas así:
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'tarea';
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pendiente';

-- Habilitar Realtime para esta tabla
ALTER PUBLICATION supabase_realtime ADD TABLE schedules;

-- ============================================================
-- Seguridad a nivel de fila (RLS)
-- La app usa la "publishable/anon key" desde el navegador, así que
-- la tabla necesita politicas que permitan leer y escribir con esa
-- clave. Sin estas politicas, todas las operaciones fallan.
-- ============================================================
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir lectura publica" ON schedules;
CREATE POLICY "Permitir lectura publica"
  ON schedules FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "Permitir escritura publica" ON schedules;
CREATE POLICY "Permitir escritura publica"
  ON schedules FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir actualizacion publica" ON schedules;
CREATE POLICY "Permitir actualizacion publica"
  ON schedules FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir borrado publico" ON schedules;
CREATE POLICY "Permitir borrado publico"
  ON schedules FOR DELETE
  TO anon, authenticated
  USING (true);

-- ============================================================
-- Tabla de Auditoria (usada por el panel "Registro de Cambios"
-- que solo ve el admin dentro de la app). Registra quien hizo
-- cada cambio (crear / actualizar / borrar) en el horario.
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cell_key TEXT,
    action TEXT,
    old_data JSONB,
    new_data JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Si la tabla ya existia sin estas columnas, agregalas asi:
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS grade TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS week_number INTEGER;

-- Igual que en "schedules": la app usa la clave anon desde el
-- navegador, asi que necesita politicas explicitas para leer e
-- insertar logs. IMPORTANTE (nota honesta): como no hay login real
-- de Supabase (el login de esta app es propio, via login_user()),
-- estas politicas no pueden restringir la LECTURA solo a quien es
-- admin dentro de la app -- cualquiera con la anon key tecnicamente
-- podria leer la tabla directamente. Quien ve el panel dentro de la
-- app SI esta restringido (solo currentUser.isAdmin), igual que pasa
-- con el resto de la seguridad "de admin" en este proyecto.
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir lectura de logs" ON audit_logs;
CREATE POLICY "Permitir lectura de logs"
  ON audit_logs FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "Permitir insertar logs" ON audit_logs;
CREATE POLICY "Permitir insertar logs"
  ON audit_logs FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);
