-- ============================================================
-- 02 — NOTIFICACIONES PUSH — ejecutar DESPUÉS de "01_actividades.sql"
-- ============================================================
-- Qué hace este archivo (misma arquitectura que antes):
--   1) Tabla para guardar los dispositivos que activaron notificaciones.
--   2) Un lugar privado (no accesible desde el navegador) para guardar
--      la URL de la Edge Function y un secreto compartido con ella.
--   3) Funciones que arman el TEXTO de cada notificación con los datos
--      de la actividad (actividad a realizar, fecha, hora, plazo, notas).
--   4) Un trigger: cuando se crea o cambia una actividad, se avisa.
--   5) pg_cron: al inicio de cada hora, si hay una actividad en esa
--      franja, se avisa.
--   6) pg_cron: todos los días a las 5:30 a. m. (hora Bogotá) se manda
--      el resumen de actividades del día.
--
-- IMPORTANTE: antes de correr esto, ten a la mano:
--   - La URL de tu Edge Function:
--     https://TU_PROJECT_REF.supabase.co/functions/v1/send-push
--   - Un secreto (texto largo y aleatorio) que también configurarás como
--     variable CRON_SECRET en la función (ver README.md).
-- ============================================================

-- 1) Suscripciones push (una fila por dispositivo/navegador) ---------
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text unique not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "anon puede suscribirse" on public.push_subscriptions;
create policy "anon puede suscribirse"
  on public.push_subscriptions for insert
  to anon, authenticated
  with check (true);

drop policy if exists "anon puede actualizar su suscripcion" on public.push_subscriptions;

drop policy if exists "anon puede darse de baja" on public.push_subscriptions;
create policy "anon puede darse de baja"
  on public.push_subscriptions for delete
  to anon, authenticated
  using (true);
-- (Sin políticas de SELECT ni UPDATE para anon: el navegador no puede
-- listar ni modificar suscripciones existentes. Un endpoint duplicado
-- se trata como ya registrado; la Edge Function usa service_role para leer.)
revoke update on table public.push_subscriptions from anon, authenticated;

-- 2) Configuración privada (URL de la función + secreto) --------------
create schema if not exists private;

create table if not exists private.app_secrets (
  key text primary key,
  value text not null
);
alter table private.app_secrets enable row level security;
-- Sin políticas = nadie vía API puede leer esta tabla. Solo funciones
-- SECURITY DEFINER (dueñas: postgres) pueden acceder a ella.

-- >>> REEMPLAZA estos dos valores por los tuyos antes de ejecutar <<<
insert into private.app_secrets (key, value) values
  ('edge_function_url', 'https://TU_PROJECT_REF.supabase.co/functions/v1/send-push'),
  ('cron_secret', 'REEMPLAZA-POR-UN-SECRETO-LARGO-Y-ALEATORIO')
on conflict (key) do update set value = excluded.value;

-- Extensiones necesarias para llamar HTTP desde Postgres y programar tareas
create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron with schema extensions;

-- Función que llama a la Edge Function (uso interno, no expuesta)
create or replace function private.notify_push(payload jsonb)
returns void
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_url text;
  v_secret text;
begin
  select value into v_url    from private.app_secrets where key = 'edge_function_url';
  select value into v_secret from private.app_secrets where key = 'cron_secret';

  if v_url is null or v_url like '%REEMPLAZA%' then
    raise notice 'notify_push: configura edge_function_url en private.app_secrets antes de usar notificaciones';
    return;
  end if;

  perform net.http_post(
    url := v_url,
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
    body := payload
  );
end;
$$;
revoke all on function private.notify_push(jsonb) from public;

-- 3) Textos de las notificaciones ------------------------------------

-- "Lunes 5 de octubre"
create or replace function public.fecha_larga(p_fecha date)
returns text language sql immutable as $$
  select (array['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'])[extract(isodow from p_fecha)::int]
         || ' ' || extract(day from p_fecha)::int || ' de '
         || (array['enero','febrero','marzo','abril','mayo','junio','julio','agosto',
                   'septiembre','octubre','noviembre','diciembre'])[extract(month from p_fecha)::int];
$$;

-- 8 -> "8:00 a. m."   |   0 -> "12:00 a. m."   |   13 -> "1:00 p. m."
create or replace function public.hora_12(p_hora int)
returns text language sql immutable as $$
  select (case when p_hora % 12 = 0 then 12 else p_hora % 12 end)::text
         || ':00 ' || (case when p_hora % 24 < 12 then 'a. m.' else 'p. m.' end);
$$;

-- 8 -> "8:00 a. m. - 9:00 a. m."   |   23 -> "11:00 p. m. - 12:00 a. m."
create or replace function public.rango_hora(p_hora int)
returns text language sql immutable as $$
  select public.hora_12(p_hora) || ' - ' || public.hora_12((p_hora + 1) % 24);
$$;

-- Cuerpo común de la notificación de UNA actividad:
--   Actividad a realizar: texto · 🕐 hora · 📅 fecha · plazo · (notas si hay)
create or replace function public.actividad_texto(a public.actividades)
returns text language sql stable as $$
  select 'Actividad a realizar: '
      || left(regexp_replace(btrim(coalesce(a.que_hacer, '')), '[[:space:]]+', ' ', 'g'), 500)
      || E'\n🕐 ' || public.rango_hora(a.hora::int)
      || ' · 📅 ' || public.fecha_larga(a.fecha) || E'\n'
      || '¿Tiene plazo? '
      || (case when a.tiene_plazo and a.fecha_plazo is not null
               then 'Sí, hasta el ' || lower(public.fecha_larga(a.fecha_plazo))
               else 'No' end)
      || (case when btrim(coalesce(a.notas_generales, '')) <> ''
               then E'\n\n📝 Notas: ' || left(btrim(a.notas_generales), 200)
               else '' end);
$$;

-- 4) Trigger: actividad nueva o con cambios -----------------------------
create or replace function public.trg_actividad_change()
returns trigger
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_is_new boolean;
  v_meaningful_change boolean;
  v_title text;
begin
  if TG_OP = 'DELETE' then
    return old;
  end if;

  if NEW.que_hacer is null or btrim(NEW.que_hacer) = '' then
    return NEW; -- solo notas / se vació la actividad: no notificar
  end if;

  v_is_new := (TG_OP = 'INSERT');

  v_meaningful_change :=
    v_is_new
    or (OLD.que_hacer   is distinct from NEW.que_hacer)
    or (OLD.tiene_plazo is distinct from NEW.tiene_plazo)
    or (OLD.fecha_plazo is distinct from NEW.fecha_plazo);

  if not v_meaningful_change then
    return NEW; -- p. ej. solo cambiaron las notas: sin aviso
  end if;

  if v_is_new then
    v_title := '📌 Nueva actividad';
  else
    v_title := '✏️ Actividad modificada';
  end if;

  perform private.notify_push(jsonb_build_object(
    'title', v_title,
    'body', public.actividad_texto(NEW),
    'tag', 'actividad-' || NEW.fecha || '-' || NEW.hora,
    'urgency', 'high',
    'url', './'
  ));

  return NEW;
end;
$$;

drop trigger if exists on_actividad_change on public.actividades;
create trigger on_actividad_change
after insert or update on public.actividades
for each row execute function public.trg_actividad_change();

-- 5) Aviso al empezar cada franja horaria, si hay actividad -------------
-- p_ahora solo existe para poder probar la función; el cron la llama sin argumentos.
create or replace function public.notify_activity_start(p_ahora timestamptz default now())
returns void
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_local timestamp := p_ahora at time zone 'America/Bogota';
  v_row public.actividades%rowtype;
begin
  select * into v_row
  from public.actividades
  where fecha = v_local::date
    and hora = extract(hour from v_local)::int;

  if not found or v_row.que_hacer is null or btrim(v_row.que_hacer) = '' then
    return; -- no hay actividad para esta franja
  end if;

  perform private.notify_push(jsonb_build_object(
    'title', '📚 Actividad próxima',
    'body', public.actividad_texto(v_row),
    'tag', 'actividad-inicio-' || v_row.hora,
    'urgency', 'high',
    'url', './'
  ));
end;
$$;

-- 6) Resumen diario a las 5:30 a. m. (hora Bogotá) ------------------------
create or replace function public.notify_daily_summary(p_ahora timestamptz default now())
returns void
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_hoy date := (p_ahora at time zone 'America/Bogota')::date;
  v_lines text := '';
  v_count int := 0;
  r record;
begin
  for r in
    select * from public.actividades
    where fecha = v_hoy
      and que_hacer is not null and btrim(que_hacer) <> ''
    order by hora
  loop
    v_lines := v_lines
      || '• ' || public.rango_hora(r.hora::int) || ': ' || left(btrim(r.que_hacer), 90)
      || (case when r.tiene_plazo and r.fecha_plazo is not null
               then ' (plazo: ' || to_char(r.fecha_plazo, 'DD/MM/YYYY') || ')'
               else '' end)
      || E'\n';
    v_count := v_count + 1;
  end loop;

  if v_count = 0 then
    v_lines := 'No tienes actividades para hoy. ¡Buen día! 🎉';
  end if;

  perform private.notify_push(jsonb_build_object(
    'title', '☀️ Actividades de hoy (' || v_count || ')',
    'body', '📅 ' || public.fecha_larga(v_hoy) || E'\n\n' || v_lines,
    'tag', 'daily-summary',
    'urgency', 'high',
    'url', './'
  ));
end;
$$;

-- 7) Programar los avisos con pg_cron -----------------------------------
-- Bogotá es UTC-5 todo el año (sin horario de verano). Como el desfase es
-- de horas exactas, "al inicio de cada hora" en UTC es también "al inicio
-- de cada hora" en Bogotá, y la función calcula la hora local sola.
do $$
declare
  v_jobname text;
begin
  for v_jobname in
    select unnest(array['daily-activities-summary', 'activity-start-hourly'])
  loop
    perform cron.unschedule(jobid) from cron.job where jobname = v_jobname;
  end loop;
end $$;

-- Resumen diario: 5:30 a. m. Bogotá = 10:30 UTC
select cron.schedule('daily-activities-summary', '30 10 * * *',
  $$select public.notify_daily_summary();$$);

-- Inicio de cada franja: minuto 0 de cada hora, los 7 días de la semana
select cron.schedule('activity-start-hourly', '0 * * * *',
  $$select public.notify_activity_start();$$);
